language: java
jdk:
  - oraclejdk8

sudo: required

install:
  - sudo sh -c 'echo "deb https://sdkrepo.atlassian.com/debian/ stable contrib" >>/etc/apt/sources.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys B07804338C015B73
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install atlassian-plugin-sdk

script:
  - sudo atlas-package
